### ISSUE TITLE
refrain multiple times the difference between cache.ram and ANY other cache

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py-book#345]
see https://github.com/web2py/web2py/issues/1421

**Comment by abastardi** [comment]
Would be interested to see a reply to https://github.com/web2py/web2py/issues/1421#issuecomment-248751354 before doing anything in the docs.

**Comment by abastardi** [comment]
Based on the discussion, looks like this isn't really an issue. Will close for now.
