### ISSUE TITLE
on_define example is not relevent 

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py-book#353]
Here : http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#on_define

Example could be improve by using proper case where the example would use a set and IS_IN_DB()...

Also, I think there is a mistake as table is not specify and on_define seems to be declared outside define_table... So or on_define goes inside define_table or the table name has to be provided...

Bad:

```python
on_define = \
    lambda table: [table.name.set_attributes(requires=IS_NOT_EMPTY(), default=''),
                              table.age.set_attributes(requires=IS_INT_IN_RANGE(0, 120), default=30)]
```

Good:

```python
on_define = \
    lambda table: [table.person.name.set_attributes(requires=IS_NOT_EMPTY(), default=''),
                              table.person.age.set_attributes(requires=IS_INT_IN_RANGE(0, 120), default=30)]
```

??

**Comment by abastardi** [comment]
No, the `Table` object is what gets passed into the `on_define` callback, so you would not add the table name to it. `table.person.name` is incorrect -- it should be `table.name`, as shown in the book.

**Comment by BuhtigithuB** [comment]
It seems to work either case... not the right place to discuss lengthy
about that, but I don't understand how it works, I mean it not mention in
the book if the on_define callback has to be place after the table, it's
required to be place just after or it wouldn't be possible to disambiguate
a field that would be used in multiples tables with need for different
requires validator...

??

**Comment by BuhtigithuB** [comment]
I think I understand on_define called from the table definition... No I
don't :) It means the on_define for a given field will be the requires that
will be set for all the table...

On Wed, Mar 15, 2017 at 6:10 PM, Richard Vézina <ml.richard.vezina@gmail.com

**Comment by abastardi** [comment]
Here is the code that calls `on_define`: https://github.com/web2py/pydal/blob/32cde26be1913c67738f21f1a674f5dadfe72a8a/pydal/base.py#L626

It is called within the `lazy_define_table` method of `DAL`, which is the function that fully defines the table. At the end of that function, the `Table` object itself is passed to your `on_define` callback. Within that callback, you can do whatever you want to the table, including accessing any of its fields and modifying them. The callback does not have to be a `lambda` function -- it can be a complex function that does anything to the table.

**Comment by BuhtigithuB** [comment]
So, it is as I as was explaining on_define is a argument of define_table, the book example is wrong...

Book example: 
```python
db = DAL(lazy_tables=True)
db.define_table('person',
                Field('name'),
                Field('age', 'integer'))

on_define=lambda table: [table.name.set_attributes(requires=IS_NOT_EMPTY(), default=''),
                         table.age.set_attributes(requires=IS_INT_IN_RANGE(0, 120), default=30)]
```

Should be:

```python
db = DAL(lazy_tables=True)
db.define_table('person',
                Field('name'),
                Field('age', 'integer'),
                on_define=lambda table: [table.name.set_attributes(requires=IS_NOT_EMPTY(), default=''),
                                         table.age.set_attributes(requires=IS_INT_IN_RANGE(0, 120), default=30)]
               )
```

That why I was puzzled by not passing table name...

**Comment by abastardi** [comment]
Yes, that should be corrected.

**Comment by BuhtigithuB** [comment]
Will send a PR ASAP or you can do it if you have time.
