### ISSUE TITLE
Document how to insert 4-byte characters using MySQL connector

### ISSUE THREAD

**Issue by hyanwong** [web2py/web2py-book#372]
Moved from https://github.com/web2py/web2py/issues/1838, which discusses the problem of needing bespoke settings to properly save utf8 when using mysql (see https://mathiasbynens.be/notes/mysql-utf8mb4). To avoid error messages like `Invalid utf8 character string:` in web2py it seems it is necessary to use set_encoding in appconfig.ini, as in

```
mysql://username:password@localhost/test?set_encoding=utf8mb4
```

See https://stackoverflow.com/a/39353494. (Also you must set the collation to utf8mb4 on the relevant table and column). Can this be officially documented somewhere please?

**Comment by BuhtigithuB** [comment]
@hyanwong, Can you add a note some where in the book where it gonna be relevant and submit a PR?
