### ISSUE TITLE
Web2py online book page is returning an error

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py-book#415]
Web2py online book page is returning an error

Internal error
Ticket issued: books/178.166.36.79.2019-03-13.09-10-57.75ae8466-170e-4585-92bb-608882e50879

with this URL

http://web2py.com/books/default/search/29?search=signature

**Comment by nicozanf** [comment]
The error is not present anymore, I think we can close the issue

**Comment by jcrmatos** [comment]
Yes, you're correct.
